### PR TITLE
add pandoc_args

### PR DESCRIPTION
**Pull request by julianre**
I want to use pandoc-crossref with mediawiki_document. I added the pandoc_args argument and handed it to pandoc_options.

### CODE REVIEW

**Comment by dpprdan** [comment]
Sorry for the delay, I lost sight of this over the holidays, but this is great, thanks! 

Could you please add documentation for `pandoc_args`, e.g. like 
```r
#' @param pandoc_args Additional command line options to pass to pandoc.
```

Could you also please add `pandoc_args` to `textile_document()` as well? Also with documentation, please, but you can take a shortcut by just [adding](https://r-pkgs.org/man.html#inheriting-parameters-from-other-functions)
```r
#' @inheritParams mediawiki_document
```
(and deleting the `@param keep_md` [line](https://github.com/dpprdan/rmdwiki/blob/faddc08d30db059556e4f1218b2af61e6717fa56/R/textile_document.R#L5)), like I already should have.

Also feel free to add yourself as contributor in DESCRIPTION if you like.

**Comment by julianre** [comment]
I added the documentation (like I should have done in the first place). I hope everything is fine this way.

**Comment by dpprdan** [comment]
🚀 Thanks a lot! 🚀

**Comment by julianre** [comment]
Could you recompile the help files (don't know, if this is the right term, the roxygen thing :-D) ?

**Comment by dpprdan** [comment]
Good call! Done.

> don't know, if this is the right term

I'd say roxygenise, after `roxygen2::roxygenise()` 😉.

**Comment by julianre** [comment]
I'll add it to my vocabulary 😀

**Pull request merged**
