### PR TITLE
add dokuwiki

### PR DESCRIPTION
**Pull request by drmowinckels**

### CODE REVIEW

**Comment by dpprdan** [comment]
Thanks! Do you want to add yourself as contributor?

**Comment by drmowinckels** [comment]
Sure, thanks for the prompt! I also added a simple github action for testing the package in push/pull, which can be convenient.

**Comment by dpprdan** [comment]
> I also added a simple github action for testing the package in push/pull, which can be convenient.

I did that as well last night (though only the [check-release](https://github.com/r-lib/actions/blob/v2-branch/examples/check-release.yaml) workflow), so I'll revert that commit. 

(BTW, the current r-lib actions have been continually updated. Current version are in the [v2-branch](https://github.com/r-lib/actions/tree/v2-branch) (current default branch) in the https://github.com/r-lib/actions repo. I just noticed that your workflow contained `v1` actions and they are now all updated to `v2`.)

Thanks again and I'll merge in a minute.

**Pull request merged**
